from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf


BASE_DIR = Path(__file__).resolve().parent.parent
RAW_DIR = BASE_DIR / "raw"
PROCESSED_DIR = BASE_DIR / "processed"

POSTS_XML = RAW_DIR / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Posts.xml"
COMMENTS_XML = RAW_DIR / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Comments.xml"
POST_CANDIDATES = PROCESSED_DIR / "who_still_answers_disclosed_ai_post_candidates.txt"
COMMENT_CANDIDATES = PROCESSED_DIR / "who_still_answers_disclosed_ai_comment_candidates.txt"

ANSWERS_PARQUET = PROCESSED_DIR / "stackexchange_20251231_focal_answers.parquet"

DISCLOSURES_CSV = PROCESSED_DIR / "who_still_answers_disclosure_fe_disclosures.csv"
USER_MONTH_PANEL = PROCESSED_DIR / "who_still_answers_disclosure_fe_user_month_panel.csv"
BEFORE_AFTER_RESULTS = PROCESSED_DIR / "who_still_answers_disclosure_fe_before_after_results.csv"
EVENT_TIME_RESULTS = PROCESSED_DIR / "who_still_answers_disclosure_fe_event_time_results.csv"
SUMMARY_JSON = PROCESSED_DIR / "who_still_answers_disclosure_fe_summary.json"

AI_PATTERNS = {
    "chatgpt": r"\bchatgpt\b",
    "copilot": r"\b(?:github\s+)?copilot\b",
    "claude": r"\bclaude(?:\s+code|\s+ai)?\b|claude-code|claude code",
    "deepseek": r"\bdeepseek\b",
    "openai": r"\bopenai\b",
    "anthropic": r"\banthropic\b",
    "gemini": r"\b(?:google\s+)?gemini(?:\s+(?:ai|pro|flash|nano|1\.5|2(?:\.0)?))?\b",
    "bard": r"\bgoogle\s+bard\b|\bbard\s+ai\b",
    "llm": r"\blarge language model(?:s)?\b|\bllm(?:s)?\b",
    "gpt_family": r"\bgpt[- ]?(?:3|3\.5|4|4o|4\.1|4\.5|5|o1|o3|o4)\b|\bgenerative pre[- ]trained\b",
    "ai_generated": r"\b(?:ai[- ]generated|generated by (?:chatgpt|openai|ai)|written by (?:chatgpt|openai|ai)|created by (?:chatgpt|openai|ai))\b",
}
COARSE_HINT = re.compile(
    r"chatgpt|copilot|openai|anthropic|claude|deepseek|gemini|bard|llm|gpt|language model|ai-generated",
    flags=re.IGNORECASE,
)

EVENT_WINDOW = (-6, 6)
MIN_ANSWERS_PER_USER = 2


def compile_patterns() -> dict[str, re.Pattern[str]]:
    return {label: re.compile(pattern, flags=re.IGNORECASE) for label, pattern in AI_PATTERNS.items()}


def match_text(text: str, compiled: dict[str, re.Pattern[str]]) -> list[str]:
    if not text:
        return []
    return [label for label, pattern in compiled.items() if pattern.search(text)]


def _regex_attr(pattern: re.Pattern[str], text: str) -> str | None:
    match = pattern.search(text)
    return match.group(1) if match else None


def iter_xml_hits(source_path: Path, compiled: dict[str, re.Pattern[str]], kind: str) -> list[dict[str, object]]:
    hits: list[dict[str, object]] = []
    if not source_path.exists():
        return hits
    if kind == "post":
        post_type_re = re.compile(r'PostTypeId="(\d+)"')
        owner_re = re.compile(r'OwnerUserId="(\d+)"')
        created_re = re.compile(r'CreationDate="([^"]+)"')
        id_re = re.compile(r'Id="(\d+)"')
        body_re = re.compile(r'Body="([^"]*)"')
    else:
        user_re = re.compile(r'UserId="(\d+)"')
        created_re = re.compile(r'CreationDate="([^"]+)"')
        post_re = re.compile(r'PostId="(\d+)"')
        text_re = re.compile(r'Text="([^"]*)"')
    with source_path.open("r", encoding="utf-8", errors="ignore", buffering=1024 * 1024) as handle:
        for line in handle:
            if "<row " not in line or COARSE_HINT.search(line) is None:
                continue
            if kind == "post":
                post_type = _regex_attr(post_type_re, line)
                if post_type != "2":
                    continue
                raw_user = _regex_attr(owner_re, line)
                if raw_user is None:
                    continue
                body = _regex_attr(body_re, line) or ""
                matches = match_text(body, compiled)
                if not matches:
                    continue
                created_at = _regex_attr(created_re, line)
                if created_at is None:
                    continue
                hits.append(
                    {
                        "user_id": int(raw_user),
                        "created_at": created_at,
                        "source": "answer_post",
                        "post_id": int(_regex_attr(id_re, line) or 0) or None,
                        "labels": ";".join(sorted(matches)),
                    }
                )
            else:
                raw_user = _regex_attr(user_re, line)
                if raw_user is None:
                    continue
                text = _regex_attr(text_re, line) or ""
                matches = match_text(text, compiled)
                if not matches:
                    continue
                created_at = _regex_attr(created_re, line)
                if created_at is None:
                    continue
                hits.append(
                    {
                        "user_id": int(raw_user),
                        "created_at": created_at,
                        "source": "comment",
                        "post_id": int(_regex_attr(post_re, line) or 0) or None,
                        "labels": ";".join(sorted(matches)),
                    }
                )
    return hits


def load_disclosures() -> pd.DataFrame:
    if DISCLOSURES_CSV.exists():
        cached = pd.read_csv(DISCLOSURES_CSV)
        cached["created_at"] = pd.to_datetime(cached["created_at"], utc=True, errors="coerce")
        cached = cached.dropna(subset=["created_at"]).copy()
        return cached
    compiled = compile_patterns()
    post_source = POST_CANDIDATES if POST_CANDIDATES.exists() else POSTS_XML
    comment_source = COMMENT_CANDIDATES if COMMENT_CANDIDATES.exists() else COMMENTS_XML
    post_hits = iter_xml_hits(post_source, compiled, "post")
    comment_hits = iter_xml_hits(comment_source, compiled, "comment")
    if not post_hits and not comment_hits:
        return pd.DataFrame()
    hits = pd.DataFrame(post_hits + comment_hits)
    hits["created_at"] = pd.to_datetime(hits["created_at"], utc=True, errors="coerce")
    hits = hits.dropna(subset=["created_at"]).copy()
    hits = hits.sort_values(["user_id", "created_at"]).reset_index(drop=True)
    hits.to_csv(DISCLOSURES_CSV, index=False)
    return hits


def load_answers() -> pd.DataFrame:
    answers = pd.read_parquet(ANSWERS_PARQUET).copy()
    answers["answer_created_at"] = pd.to_datetime(answers["answer_created_at"], utc=True, errors="coerce")
    answers["owner_user_id"] = pd.to_numeric(answers["owner_user_id"], errors="coerce")
    answers = answers.dropna(subset=["answer_created_at", "owner_user_id"]).copy()
    answers["owner_user_id"] = answers["owner_user_id"].astype("int64")
    answers["score"] = pd.to_numeric(answers["score"], errors="coerce").fillna(0.0)
    return answers


def add_role_flags(answers: pd.DataFrame) -> pd.DataFrame:
    sorted_first = answers.sort_values(["question_id", "answer_created_at", "answer_id"]).drop_duplicates("question_id")
    first_ids = set(sorted_first["answer_id"].tolist())

    sorted_top = answers.sort_values(
        ["question_id", "score", "answer_created_at", "answer_id"], ascending=[True, False, True, True]
    ).drop_duplicates("question_id")
    top_ids = set(sorted_top["answer_id"].tolist())

    positive = answers.loc[answers["score"] > 0].copy()
    sorted_positive = positive.sort_values(["question_id", "answer_created_at", "answer_id"]).drop_duplicates("question_id")
    positive_ids = set(sorted_positive["answer_id"].tolist())

    answers = answers.copy()
    answers["is_first_answer"] = answers["answer_id"].isin(first_ids).astype(int)
    answers["is_top_score"] = answers["answer_id"].isin(top_ids).astype(int)
    answers["is_first_positive"] = answers["answer_id"].isin(positive_ids).astype(int)
    answers["is_accepted_current"] = pd.to_numeric(answers["is_current_accepted_answer"], errors="coerce").fillna(0).astype(int)
    return answers


def month_diff(answer_month: str, disclosure_month: str) -> int:
    answer_period = pd.Period(answer_month, freq="M")
    disclosure_period = pd.Period(disclosure_month, freq="M")
    return int((answer_period.year - disclosure_period.year) * 12 + (answer_period.month - disclosure_period.month))


def build_user_month_panel(answers: pd.DataFrame, disclosures: pd.DataFrame) -> pd.DataFrame:
    if disclosures.empty:
        return pd.DataFrame()
    first_disclosure = (
        disclosures.groupby("user_id", as_index=False)["created_at"].min().rename(columns={"user_id": "owner_user_id"})
    )
    answers = answers.copy()
    answers["answer_month"] = answers["answer_created_at"].dt.strftime("%Y-%m")
    panel = (
        answers.groupby(["owner_user_id", "answer_month"], as_index=False)
        .agg(
            n_answers=("answer_id", "size"),
            accepted_share=("is_accepted_current", "mean"),
            top_score_share=("is_top_score", "mean"),
            first_answer_share=("is_first_answer", "mean"),
            first_positive_share=("is_first_positive", "mean"),
            mean_score=("score", "mean"),
        )
    )
    panel = panel.merge(first_disclosure, on="owner_user_id", how="inner")
    panel["disclosure_month"] = panel["created_at"].dt.strftime("%Y-%m")
    panel["rel_month"] = panel.apply(
        lambda row: month_diff(row["answer_month"], row["disclosure_month"]),
        axis=1,
    )
    panel["post_disclosure"] = (panel["rel_month"] >= 0).astype(int)
    panel = panel.sort_values(["owner_user_id", "answer_month"]).reset_index(drop=True)
    return panel


def filter_user_panel(panel: pd.DataFrame) -> pd.DataFrame:
    if panel.empty:
        return panel
    counts = panel.groupby("owner_user_id", as_index=False)["n_answers"].sum()
    eligible = counts.loc[counts["n_answers"] >= MIN_ANSWERS_PER_USER, "owner_user_id"]
    panel = panel.loc[panel["owner_user_id"].isin(eligible)].copy()
    user_span = panel.groupby("owner_user_id", as_index=False)["rel_month"].agg(["min", "max"]).reset_index()
    user_span["has_pre"] = user_span["min"] < 0
    user_span["has_post"] = user_span["max"] >= 0
    eligible_users = user_span.loc[user_span["has_pre"] & user_span["has_post"], "owner_user_id"]
    panel = panel.loc[panel["owner_user_id"].isin(eligible_users)].copy()
    return panel


def fit_before_after(panel: pd.DataFrame, outcomes: list[str]) -> pd.DataFrame:
    rows = []
    if panel.empty:
        return pd.DataFrame()
    for outcome in outcomes:
        model = smf.wls(
            f"{outcome} ~ post_disclosure + C(owner_user_id) + C(answer_month)",
            data=panel,
            weights=panel["n_answers"],
        ).fit(
            cov_type="cluster",
            cov_kwds={"groups": panel["owner_user_id"], "use_correction": True, "df_correction": True},
        )
        rows.append(
            {
                "outcome": outcome,
                "coef": float(model.params.get("post_disclosure", np.nan)),
                "se": float(model.bse.get("post_disclosure", np.nan)),
                "pval": float(model.pvalues.get("post_disclosure", np.nan)),
                "n_user_months": int(len(panel)),
                "n_users": int(panel["owner_user_id"].nunique()),
            }
        )
    results = pd.DataFrame(rows)
    results.to_csv(BEFORE_AFTER_RESULTS, index=False)
    return results


def fit_event_time(panel: pd.DataFrame, outcomes: list[str]) -> pd.DataFrame:
    if panel.empty:
        return pd.DataFrame()
    lower, upper = EVENT_WINDOW
    window = panel.loc[(panel["rel_month"] >= lower) & (panel["rel_month"] <= upper)].copy()
    if window.empty:
        return pd.DataFrame()
    window["rel_month_str"] = window["rel_month"].astype(int).astype(str)
    rows = []
    for outcome in outcomes:
        try:
            model = smf.wls(
                f"{outcome} ~ C(rel_month_str, Treatment(reference='-1')) + C(owner_user_id) + C(answer_month)",
                data=window,
                weights=window["n_answers"],
            ).fit(
                cov_type="cluster",
                cov_kwds={"groups": window["owner_user_id"], "use_correction": True, "df_correction": True},
            )
        except Exception:
            continue
        for term, coef in model.params.items():
            if "C(rel_month_str" not in term:
                continue
            rel_value = term.split("T.", 1)[1].split("]", 1)[0] if "T." in term else term
            rows.append(
                {
                    "outcome": outcome,
                    "rel_month": int(rel_value),
                    "coef": float(coef),
                    "se": float(model.bse.get(term, np.nan)),
                    "pval": float(model.pvalues.get(term, np.nan)),
                    "n_user_months": int(len(window)),
                    "n_users": int(window["owner_user_id"].nunique()),
                }
            )
    results = pd.DataFrame(rows).sort_values(["outcome", "rel_month"])
    results.to_csv(EVENT_TIME_RESULTS, index=False)
    return results


def summarize(panel: pd.DataFrame, disclosures: pd.DataFrame, before_after: pd.DataFrame, event_time: pd.DataFrame) -> dict[str, object]:
    summary = {
        "n_disclosure_events": int(len(disclosures)),
        "n_disclosing_users": int(disclosures["user_id"].nunique()) if not disclosures.empty else 0,
        "n_user_months": int(len(panel)),
        "n_users": int(panel["owner_user_id"].nunique()) if not panel.empty else 0,
        "event_window": EVENT_WINDOW,
        "outcomes": [
            "accepted_share",
            "top_score_share",
            "first_answer_share",
            "first_positive_share",
            "mean_score",
        ],
    }
    if not before_after.empty:
        summary["before_after"] = before_after.to_dict(orient="records")
    if not event_time.empty:
        summary["event_time_rows"] = int(len(event_time))
    SUMMARY_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def main() -> None:
    disclosures = load_disclosures()
    answers = load_answers()
    answers = add_role_flags(answers)
    panel = build_user_month_panel(answers, disclosures)
    panel = filter_user_panel(panel)
    panel.to_csv(USER_MONTH_PANEL, index=False)

    outcomes = [
        "accepted_share",
        "top_score_share",
        "first_answer_share",
        "first_positive_share",
        "mean_score",
    ]
    before_after = fit_before_after(panel, outcomes)
    event_time = fit_event_time(panel, outcomes)
    summary = summarize(panel, disclosures, before_after, event_time)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
