from __future__ import annotations

import json
import re
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "processed"
RAW = ROOT / "raw"
PAPER = ROOT / "paper"

QUESTION_PANEL = PROCESSED / "stackexchange_20251231_question_level_enriched.parquet"
FOCAL_ANSWERS = PROCESSED / "stackexchange_20251231_focal_answers.parquet"
POSTS_XML = RAW / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Posts.xml"
COMMENTS_XML = RAW / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Comments.xml"
POST_CANDIDATES = PROCESSED / "who_still_answers_disclosed_ai_post_candidates.txt"
COMMENT_CANDIDATES = PROCESSED / "who_still_answers_disclosed_ai_comment_candidates.txt"

HITS_PARQUET = PROCESSED / "who_still_answers_disclosed_ai_question_hits.parquet"
HITS_CSV = PROCESSED / "who_still_answers_disclosed_ai_question_hits.csv"
COUNTS_CSV = PROCESSED / "who_still_answers_disclosed_ai_counts.csv"
TAG_MONTH_CSV = PROCESSED / "who_still_answers_disclosed_ai_tag_month_counts.csv"
SUMMARY_JSON = PROCESSED / "who_still_answers_disclosed_ai_summary.json"
MEMO_PATH = PAPER / "who_still_answers_disclosed_ai_corpus_2026-04-04.md"

AI_PATTERNS = {
    "chatgpt": r"\bchatgpt\b",
    "copilot": r"\b(?:github\s+)?copilot\b",
    "claude": r"\bclaude(?:\s+code|\s+ai)?\b|claude-code|claude code",
    "deepseek": r"\bdeepseek\b",
    "openai": r"\bopenai\b",
    "anthropic": r"\banthropic\b",
    "gemini": r"\b(?:google\s+)?gemini(?:\s+(?:ai|pro|flash|nano|1\.5|2(?:\.0)?))?\b",
    "bard": r"\bgoogle\s+bard\b|\bbard\s+ai\b",
    "llm": r"\blarge language model(?:s)?\b|\bllm(?:s)?\b",
    "gpt_family": r"\bgpt[- ]?(?:3|3\.5|4|4o|4\.1|4\.5|5|o1|o3|o4)\b|\bgenerative pre[- ]trained\b",
    "ai_generated": r"\b(?:ai[- ]generated|generated by (?:chatgpt|openai|ai)|written by (?:chatgpt|openai|ai)|created by (?:chatgpt|openai|ai))\b",
}
COARSE_HINT = re.compile(
    r"chatgpt|copilot|openai|anthropic|claude|deepseek|gemini|bard|llm|gpt|language model|ai-generated",
    flags=re.IGNORECASE,
)


def load_question_metadata() -> tuple[dict[int, dict[str, object]], set[int]]:
    cols = [
        "question_id",
        "question_created_at",
        "title",
        "primary_tag",
        "month_id",
        "high_tag",
        "exposure_index",
        "post_chatgpt",
    ]
    df = pd.read_parquet(QUESTION_PANEL, columns=cols).copy()
    df["question_id"] = df["question_id"].astype(int)
    metadata = df.set_index("question_id").to_dict("index")
    return metadata, set(metadata.keys())


def load_answer_mapping(question_ids: set[int]) -> dict[int, int]:
    answers = pd.read_parquet(FOCAL_ANSWERS, columns=["answer_id", "question_id"]).copy()
    answers["answer_id"] = answers["answer_id"].astype(int)
    answers["question_id"] = answers["question_id"].astype(int)
    answers = answers.loc[answers["question_id"].isin(question_ids)].copy()
    return dict(zip(answers["answer_id"], answers["question_id"]))


def compile_patterns() -> dict[str, re.Pattern[str]]:
    return {label: re.compile(pattern, flags=re.IGNORECASE) for label, pattern in AI_PATTERNS.items()}


def match_text(text: str, compiled: dict[str, re.Pattern[str]]) -> list[str]:
    if not text:
        return []
    return [label for label, pattern in compiled.items() if pattern.search(text)]


def init_hit_row(question_id: int, metadata: dict[int, dict[str, object]]) -> dict[str, object]:
    row = metadata[question_id].copy()
    row.update(
        {
            "question_id": question_id,
            "question_title_hit": 0,
            "question_body_hit": 0,
            "answer_body_hit": 0,
            "question_comment_hit": 0,
            "answer_comment_hit": 0,
            "n_answer_body_posts_hit": 0,
            "n_question_comments_hit": 0,
            "n_answer_comments_hit": 0,
            "any_comment_hit": 0,
            "any_hit": 0,
            "_label_sets": {
                "title": set(),
                "question_body": set(),
                "answer_body": set(),
                "question_comment": set(),
                "answer_comment": set(),
            },
        }
    )
    return row


def stream_post_hits(
    question_ids: set[int],
    answer_to_question: dict[int, int],
    metadata: dict[int, dict[str, object]],
    compiled: dict[str, re.Pattern[str]],
) -> dict[int, dict[str, object]]:
    hits: dict[int, dict[str, object]] = {}
    source_path = POST_CANDIDATES if POST_CANDIDATES.exists() else POSTS_XML
    with source_path.open("r", encoding="utf-8", errors="ignore", buffering=1024 * 1024) as handle:
        for line in handle:
            if "<row " not in line or COARSE_HINT.search(line) is None:
                continue
            try:
                attrs = ET.fromstring(line.strip()).attrib
            except ET.ParseError:
                continue
            post_type = attrs.get("PostTypeId")
            if post_type not in {"1", "2"}:
                continue
            raw_id = attrs.get("Id")
            if raw_id is None:
                continue
            post_id = int(raw_id)

            if post_type == "1" and post_id in question_ids:
                question_id = post_id
                title = metadata[question_id]["title"] if question_id in metadata else attrs.get("Title", "") or ""
                body = attrs.get("Body", "") or ""
                title_matches = match_text(title, compiled)
                body_matches = match_text(body, compiled)
                if title_matches or body_matches:
                    row = hits.setdefault(question_id, init_hit_row(question_id, metadata))
                    row["question_title_hit"] = max(row["question_title_hit"], int(bool(title_matches)))
                    row["question_body_hit"] = max(row["question_body_hit"], int(bool(body_matches)))
                    row["any_hit"] = 1
                    row["_label_sets"]["title"].update(title_matches)
                    row["_label_sets"]["question_body"].update(body_matches)

            elif post_type == "2" and post_id in answer_to_question:
                question_id = answer_to_question[post_id]
                body = attrs.get("Body", "") or ""
                body_matches = match_text(body, compiled)
                if body_matches:
                    row = hits.setdefault(question_id, init_hit_row(question_id, metadata))
                    row["answer_body_hit"] = 1
                    row["n_answer_body_posts_hit"] = int(row["n_answer_body_posts_hit"]) + 1
                    row["any_hit"] = 1
                    row["_label_sets"]["answer_body"].update(body_matches)
    return hits


def stream_comment_hits(
    hits: dict[int, dict[str, object]],
    question_ids: set[int],
    answer_to_question: dict[int, int],
    metadata: dict[int, dict[str, object]],
    compiled: dict[str, re.Pattern[str]],
) -> dict[int, dict[str, object]]:
    if not COMMENTS_XML.exists():
        return hits

    source_path = COMMENT_CANDIDATES if COMMENT_CANDIDATES.exists() else COMMENTS_XML
    with source_path.open("r", encoding="utf-8", errors="ignore", buffering=1024 * 1024) as handle:
        for line in handle:
            if "<row " not in line or COARSE_HINT.search(line) is None:
                continue
            try:
                attrs = ET.fromstring(line.strip()).attrib
            except ET.ParseError:
                continue
            raw_post_id = attrs.get("PostId")
            if raw_post_id is None:
                continue
            post_id = int(raw_post_id)

            question_id: int | None = None
            source_key: str | None = None
            if post_id in question_ids:
                question_id = post_id
                source_key = "question_comment"
            elif post_id in answer_to_question:
                question_id = answer_to_question[post_id]
                source_key = "answer_comment"

            if question_id is None:
                continue

            text = attrs.get("Text", "") or ""
            matches = match_text(text, compiled)
            if matches:
                row = hits.setdefault(question_id, init_hit_row(question_id, metadata))
                row[f"{source_key}_hit"] = 1
                row["any_comment_hit"] = 1
                row["any_hit"] = 1
                if source_key == "question_comment":
                    row["n_question_comments_hit"] = int(row["n_question_comments_hit"]) + 1
                else:
                    row["n_answer_comments_hit"] = int(row["n_answer_comments_hit"]) + 1
                row["_label_sets"][source_key].update(matches)

    return hits


def finalize_hits(hits: dict[int, dict[str, object]]) -> pd.DataFrame:
    if not hits:
        return pd.DataFrame()

    rows = []
    for row in hits.values():
        label_sets = row.pop("_label_sets")
        row["title_match_labels"] = ";".join(sorted(label_sets["title"]))
        row["question_body_match_labels"] = ";".join(sorted(label_sets["question_body"]))
        row["answer_body_match_labels"] = ";".join(sorted(label_sets["answer_body"]))
        row["question_comment_match_labels"] = ";".join(sorted(label_sets["question_comment"]))
        row["answer_comment_match_labels"] = ";".join(sorted(label_sets["answer_comment"]))
        row["n_title_labels"] = len(label_sets["title"])
        row["n_question_body_labels"] = len(label_sets["question_body"])
        row["n_answer_body_labels"] = len(label_sets["answer_body"])
        row["n_question_comment_labels"] = len(label_sets["question_comment"])
        row["n_answer_comment_labels"] = len(label_sets["answer_comment"])
        rows.append(row)
    return pd.DataFrame(rows)


def build_outputs(hits: pd.DataFrame, metadata_size: int) -> dict[str, object]:
    if hits.empty:
        summary = {
            "total_questions": metadata_size,
            "disclosed_ai_questions": 0,
            "question_title_hits": 0,
            "question_body_hits": 0,
            "answer_body_hits": 0,
            "question_comment_hits": 0,
            "answer_comment_hits": 0,
            "comments_xml_available": COMMENTS_XML.exists(),
        }
        SUMMARY_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
        return summary

    hits["question_created_at"] = pd.to_datetime(hits["question_created_at"], utc=True)
    ban_ts = pd.Timestamp("2022-12-05", tz="UTC")
    hits["pre_ban"] = (hits["question_created_at"] < ban_ts).astype(int)
    hits["post_ban"] = (hits["question_created_at"] >= ban_ts).astype(int)
    hits["non_title_thread_addition"] = (hits["question_title_hit"] == 0).astype(int)
    hits = hits.sort_values(["question_created_at", "question_id"]).reset_index(drop=True)

    hits.to_parquet(HITS_PARQUET, index=False)
    hits.to_csv(HITS_CSV, index=False)

    counts = pd.DataFrame(
        [
            ("total_questions", metadata_size),
            ("disclosed_ai_questions", int(len(hits))),
            ("question_title_hits", int(hits["question_title_hit"].sum())),
            ("question_body_hits", int(hits["question_body_hit"].sum())),
            ("answer_body_hits", int(hits["answer_body_hit"].sum())),
            ("question_comment_hits", int(hits["question_comment_hit"].sum())),
            ("answer_comment_hits", int(hits["answer_comment_hit"].sum())),
            ("any_comment_hits", int(hits["any_comment_hit"].sum())),
            ("non_title_thread_additions", int(hits["non_title_thread_addition"].sum())),
            ("pre_chatgpt_hits", int((hits["post_chatgpt"] == 0).sum())),
            ("post_chatgpt_hits", int((hits["post_chatgpt"] == 1).sum())),
            ("pre_ban_hits", int(hits["pre_ban"].sum())),
            ("post_ban_hits", int(hits["post_ban"].sum())),
            ("comments_xml_available", int(COMMENTS_XML.exists())),
        ],
        columns=["metric", "value"],
    )
    counts.to_csv(COUNTS_CSV, index=False)

    tag_month = (
        hits.groupby(["primary_tag", "month_id"], as_index=False)
        .agg(
            disclosed_ai_questions=("question_id", "size"),
            question_title_hits=("question_title_hit", "sum"),
            question_body_hits=("question_body_hit", "sum"),
            answer_body_hits=("answer_body_hit", "sum"),
            comment_hits=("any_comment_hit", "sum"),
            exposure_index=("exposure_index", "first"),
            high_tag=("high_tag", "first"),
        )
    )
    tag_month.to_csv(TAG_MONTH_CSV, index=False)

    label_counter = Counter()
    for col in [
        "title_match_labels",
        "question_body_match_labels",
        "answer_body_match_labels",
        "question_comment_match_labels",
        "answer_comment_match_labels",
    ]:
        for labels in hits[col].tolist():
            if labels:
                label_counter.update(labels.split(";"))

    summary = {
        "total_questions": metadata_size,
        "disclosed_ai_questions": int(len(hits)),
        "disclosed_ai_share": float(len(hits) / metadata_size),
        "question_title_hits": int(hits["question_title_hit"].sum()),
        "question_body_hits": int(hits["question_body_hit"].sum()),
        "answer_body_hits": int(hits["answer_body_hit"].sum()),
        "question_comment_hits": int(hits["question_comment_hit"].sum()),
        "answer_comment_hits": int(hits["answer_comment_hit"].sum()),
        "any_comment_hits": int(hits["any_comment_hit"].sum()),
        "non_title_thread_additions": int(hits["non_title_thread_addition"].sum()),
        "pre_chatgpt_hits": int((hits["post_chatgpt"] == 0).sum()),
        "post_chatgpt_hits": int((hits["post_chatgpt"] == 1).sum()),
        "pre_ban_hits": int(hits["pre_ban"].sum()),
        "post_ban_hits": int(hits["post_ban"].sum()),
        "comments_xml_available": COMMENTS_XML.exists(),
        "top_patterns": label_counter.most_common(10),
        "top_tags": (
            hits.groupby("primary_tag")
            .size()
            .sort_values(ascending=False)
            .head(12)
            .rename("hits")
            .to_dict()
        ),
    }
    SUMMARY_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def write_memo(summary: dict[str, object]) -> None:
    lines = [
        "# Same-Setting Disclosed-AI Corpus",
        "",
        "Date: April 4, 2026",
        "",
        "## Design",
        "",
        "This build expands the earlier title-only disclosed-AI prototype into a thread-level corpus using the local `2025Q4` Stack Overflow dump.",
        "The detector now scans question titles, question bodies, answer bodies, question comments, and answer comments.",
        "Pattern matching was also tightened to reduce obvious false positives from non-AI technical terms.",
        "",
        "## Topline",
        "",
        f"- total focal questions scanned: `{summary['total_questions']:,}`",
        f"- disclosed-AI questions: `{summary['disclosed_ai_questions']:,}`",
        f"- disclosed-AI share: `{summary['disclosed_ai_share']:.4%}`",
        f"- question-title hits: `{summary['question_title_hits']:,}`",
        f"- question-body hits: `{summary['question_body_hits']:,}`",
        f"- answer-body hits: `{summary['answer_body_hits']:,}`",
        f"- question-comment hits: `{summary['question_comment_hits']:,}`",
        f"- answer-comment hits: `{summary['answer_comment_hits']:,}`",
        f"- non-title thread additions beyond the title-only prototype: `{summary['non_title_thread_additions']:,}`",
        f"- pre-ChatGPT hits: `{summary['pre_chatgpt_hits']:,}`",
        f"- post-ChatGPT hits: `{summary['post_chatgpt_hits']:,}`",
        f"- pre-ban hits: `{summary['pre_ban_hits']:,}`",
        f"- post-ban hits: `{summary['post_ban_hits']:,}`",
        f"- comments available locally: `{summary['comments_xml_available']}`",
        "",
        "## Read",
        "",
        "This is still not a full same-setting direct-AI measurement layer, because disclosure remains selective.",
        "It is materially stronger than the earlier build because it now works at the question-thread level and includes comment-layer disclosures.",
        "That makes it a stronger base for reviewer-facing timing and direct-observation discussion than the earlier title-plus-body corpus.",
        "",
        "## Files",
        "",
        f"- hits parquet: `{HITS_PARQUET}`",
        f"- hits csv: `{HITS_CSV}`",
        f"- counts csv: `{COUNTS_CSV}`",
        f"- tag-month counts: `{TAG_MONTH_CSV}`",
        f"- summary json: `{SUMMARY_JSON}`",
    ]
    MEMO_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    PROCESSED.mkdir(parents=True, exist_ok=True)
    PAPER.mkdir(parents=True, exist_ok=True)

    metadata, question_ids = load_question_metadata()
    answer_to_question = load_answer_mapping(question_ids)
    compiled = compile_patterns()
    hits = stream_post_hits(question_ids, answer_to_question, metadata, compiled)
    hits = stream_comment_hits(hits, question_ids, answer_to_question, metadata, compiled)
    hit_df = finalize_hits(hits)
    summary = build_outputs(hit_df, len(question_ids))
    write_memo(summary)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
