from __future__ import annotations

import html
import json
import re
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "processed"
RAW = ROOT / "raw"
PAPER = ROOT / "paper"

QUESTION_PANEL = PROCESSED / "stackexchange_20251231_question_level_enriched.parquet"
FOCAL_ANSWERS = PROCESSED / "stackexchange_20251231_focal_answers.parquet"
POSTS_XML = RAW / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Posts.xml"
COMMENTS_XML = RAW / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Comments.xml"

POST_CANDIDATES = PROCESSED / "who_still_answers_disclosed_ai_post_candidates.txt"
COMMENT_CANDIDATES = PROCESSED / "who_still_answers_disclosed_ai_comment_candidates.txt"

QUESTION_HITS_PARQUET = PROCESSED / "who_still_answers_posthistory_direct_ai_question_hits.parquet"
QUESTION_HITS_CSV = PROCESSED / "who_still_answers_posthistory_direct_ai_question_hits.csv"
COUNTS_CSV = PROCESSED / "who_still_answers_posthistory_direct_ai_counts.csv"
TAG_MONTH_CSV = PROCESSED / "who_still_answers_posthistory_direct_ai_tag_month_counts.csv"
BAN_WINDOW_CSV = PROCESSED / "who_still_answers_posthistory_direct_ai_ban_window_counts.csv"
SUMMARY_JSON = PROCESSED / "who_still_answers_posthistory_direct_ai_summary.json"
MEMO_PATH = PAPER / "who_still_answers_posthistory_direct_ai_readout_2026-04-05.md"

BAN_TS = pd.Timestamp("2022-12-05", tz="UTC")
WINDOW_DAYS = [7, 15, 30, 45, 60, 90]

BROAD_PATTERNS = {
    "chatgpt": r"\bchatgpt\b",
    "copilot": r"\b(?:github\s+)?copilot\b",
    "claude": r"\bclaude(?:\s+code|\s+ai)?\b|claude[- ]code",
    "gemini": r"\b(?:google\s+)?gemini(?:\s+(?:ai|pro|flash|nano|1\.5|2(?:\.0)?))?\b",
    "deepseek": r"\bdeepseek\b",
    "openai": r"\bopenai\b",
    "anthropic": r"\banthropic\b",
    "bard": r"\bgoogle\s+bard\b|\bbard\s+ai\b",
    "gpt_family": r"\bgpt[- ]?(?:3|3\.5|4|4o|4\.1|4\.5|5|o1|o3|o4)\b|\bgenerative pre[- ]trained\b",
    "llm": r"\blarge language model(?:s)?\b|\bllm(?:s)?\b",
    "ai_generated": r"\b(?:ai[- ]generated|generated by (?:chatgpt|openai|ai)|written by (?:chatgpt|openai|ai)|created by (?:chatgpt|openai|ai))\b",
}

STRICT_PATTERNS = {
    "used_tool": r"\b(?:i|we|my|our)\s+(?:used|use|using|tried|ask(?:ed)?|prompt(?:ed)?|fed|gave|ran)\s+(?:chatgpt|copilot|claude|gemini|deepseek|openai|gpt(?:[- ]?\d(?:\.\d)?)?|llm|ai)\b",
    "tool_generated": r"\b(?:generated|written|produced|created|suggested|drafted)\s+(?:by|with)\s+(?:chatgpt|copilot|claude|gemini|deepseek|openai|gpt(?:[- ]?\d(?:\.\d)?)?|ai)\b",
    "from_tool": r"\b(?:from|via|using)\s+(?:chatgpt|copilot|claude|gemini|deepseek|openai|gpt(?:[- ]?\d(?:\.\d)?)?|llm)\b",
    "tool_said": r"\b(?:chatgpt|copilot|claude|gemini|deepseek|gpt(?:[- ]?\d(?:\.\d)?)?)(?:\s+(?:says|said|suggested|gave|returns?|wrote|generated))\b",
    "ai_assisted": r"\b(?:ai[- ]assisted|llm[- ]assisted|copilot[- ]generated|gpt[- ]generated)\b",
}

COARSE_HINT = re.compile(
    r"chatgpt|copilot|openai|anthropic|claude|deepseek|gemini|bard|llm|gpt|language model|ai-generated|ai assisted",
    flags=re.IGNORECASE,
)
HTML_TAG = re.compile(r"<[^>]+>")


def clean_text(text: str) -> str:
    if not text:
        return ""
    cleaned = HTML_TAG.sub(" ", text)
    cleaned = html.unescape(cleaned)
    return re.sub(r"\s+", " ", cleaned).strip()


def compile_patterns(patterns: dict[str, str]) -> dict[str, re.Pattern[str]]:
    return {label: re.compile(pattern, flags=re.IGNORECASE) for label, pattern in patterns.items()}


def match_text(text: str, compiled: dict[str, re.Pattern[str]]) -> list[str]:
    if not text:
        return []
    return [label for label, pattern in compiled.items() if pattern.search(text)]


def load_question_metadata() -> tuple[dict[int, dict[str, object]], set[int]]:
    cols = [
        "question_id",
        "question_created_at",
        "title",
        "primary_tag",
        "month_id",
        "high_tag",
        "exposure_index",
        "post_chatgpt",
        "keep_single_focal",
    ]
    q = pd.read_parquet(QUESTION_PANEL, columns=cols).copy()
    q = q.loc[q["keep_single_focal"] == 1].copy()
    q["question_id"] = q["question_id"].astype(int)
    q["question_created_at"] = pd.to_datetime(q["question_created_at"], utc=True)
    metadata = q.set_index("question_id").to_dict("index")
    return metadata, set(metadata.keys())


def load_answer_mapping(question_ids: set[int]) -> dict[int, int]:
    answers = pd.read_parquet(FOCAL_ANSWERS, columns=["answer_id", "question_id"]).copy()
    answers["answer_id"] = answers["answer_id"].astype(int)
    answers["question_id"] = answers["question_id"].astype(int)
    answers = answers.loc[answers["question_id"].isin(question_ids)].copy()
    return dict(zip(answers["answer_id"], answers["question_id"]))


def init_row(question_id: int, metadata: dict[int, dict[str, object]]) -> dict[str, object]:
    base = metadata[question_id].copy()
    base.update(
        {
            "question_id": question_id,
            "broad_title_hit": 0,
            "broad_question_body_hit": 0,
            "broad_answer_body_hit": 0,
            "broad_question_comment_hit": 0,
            "broad_answer_comment_hit": 0,
            "strict_title_hit": 0,
            "strict_question_body_hit": 0,
            "strict_answer_body_hit": 0,
            "strict_question_comment_hit": 0,
            "strict_answer_comment_hit": 0,
            "broad_any_thread_hit": 0,
            "strict_any_thread_hit": 0,
            "strict_question_side_hit": 0,
            "strict_answer_side_hit": 0,
            "broad_source_count": 0,
            "strict_source_count": 0,
            "broad_earliest_at": pd.NaT,
            "strict_earliest_at": pd.NaT,
            "broad_earliest_source": "",
            "strict_earliest_source": "",
            "_broad_labels": Counter(),
            "_strict_labels": Counter(),
        }
    )
    return base


def update_hit(
    row: dict[str, object],
    prefix: str,
    source_key: str,
    labels: list[str],
    event_ts: pd.Timestamp,
) -> None:
    if not labels:
        return

    hit_col = f"{prefix}_{source_key}_hit"
    if source_key == "title":
        hit_col = f"{prefix}_title_hit"
    elif source_key == "question_body":
        hit_col = f"{prefix}_question_body_hit"
    elif source_key == "answer_body":
        hit_col = f"{prefix}_answer_body_hit"
    elif source_key == "question_comment":
        hit_col = f"{prefix}_question_comment_hit"
    elif source_key == "answer_comment":
        hit_col = f"{prefix}_answer_comment_hit"

    if int(row[hit_col]) == 0:
        row[hit_col] = 1
        row[f"{prefix}_source_count"] = int(row[f"{prefix}_source_count"]) + 1
    row[f"{prefix}_any_thread_hit"] = 1

    if prefix == "strict":
        if source_key in {"title", "question_body", "question_comment"}:
            row["strict_question_side_hit"] = 1
        else:
            row["strict_answer_side_hit"] = 1

    earliest_col = f"{prefix}_earliest_at"
    earliest_source_col = f"{prefix}_earliest_source"
    current = row[earliest_col]
    if pd.isna(current) or event_ts < current:
        row[earliest_col] = event_ts
        row[earliest_source_col] = source_key

    counter_key = "_broad_labels" if prefix == "broad" else "_strict_labels"
    row[counter_key].update(labels)


def parse_post_rows(
    question_ids: set[int],
    answer_to_question: dict[int, int],
    metadata: dict[int, dict[str, object]],
    broad_compiled: dict[str, re.Pattern[str]],
    strict_compiled: dict[str, re.Pattern[str]],
) -> dict[int, dict[str, object]]:
    hits: dict[int, dict[str, object]] = {}
    source_path = POST_CANDIDATES if POST_CANDIDATES.exists() else POSTS_XML

    with source_path.open("r", encoding="utf-8", errors="ignore", buffering=1024 * 1024) as handle:
        for line in handle:
            if "<row " not in line or COARSE_HINT.search(line) is None:
                continue
            try:
                attrs = ET.fromstring(line.strip()).attrib
            except ET.ParseError:
                continue

            post_type = attrs.get("PostTypeId")
            if post_type not in {"1", "2"}:
                continue

            raw_id = attrs.get("Id")
            if raw_id is None:
                continue
            post_id = int(raw_id)

            if post_type == "1" and post_id in question_ids:
                qid = post_id
                created_at = metadata[qid]["question_created_at"]
                title = str(metadata[qid]["title"] or "")
                body = clean_text(attrs.get("Body", "") or "")

                row = hits.setdefault(qid, init_row(qid, metadata))
                broad_title = match_text(title, broad_compiled)
                strict_title = match_text(title, strict_compiled)
                broad_body = match_text(body, broad_compiled)
                strict_body = match_text(body, strict_compiled)
                update_hit(row, "broad", "title", broad_title, created_at)
                update_hit(row, "strict", "title", strict_title, created_at)
                update_hit(row, "broad", "question_body", broad_body, created_at)
                update_hit(row, "strict", "question_body", strict_body, created_at)

            elif post_type == "2" and post_id in answer_to_question:
                qid = answer_to_question[post_id]
                created_raw = attrs.get("CreationDate")
                if not created_raw:
                    continue
                created_at = pd.Timestamp(created_raw, tz="UTC")
                body = clean_text(attrs.get("Body", "") or "")
                broad_body = match_text(body, broad_compiled)
                strict_body = match_text(body, strict_compiled)
                if broad_body or strict_body:
                    row = hits.setdefault(qid, init_row(qid, metadata))
                    update_hit(row, "broad", "answer_body", broad_body, created_at)
                    update_hit(row, "strict", "answer_body", strict_body, created_at)

    return hits


def parse_comment_rows(
    hits: dict[int, dict[str, object]],
    question_ids: set[int],
    answer_to_question: dict[int, int],
    metadata: dict[int, dict[str, object]],
    broad_compiled: dict[str, re.Pattern[str]],
    strict_compiled: dict[str, re.Pattern[str]],
) -> dict[int, dict[str, object]]:
    if not COMMENTS_XML.exists():
        return hits

    source_path = COMMENT_CANDIDATES if COMMENT_CANDIDATES.exists() else COMMENTS_XML
    with source_path.open("r", encoding="utf-8", errors="ignore", buffering=1024 * 1024) as handle:
        for line in handle:
            if "<row " not in line or COARSE_HINT.search(line) is None:
                continue
            try:
                attrs = ET.fromstring(line.strip()).attrib
            except ET.ParseError:
                continue

            raw_post_id = attrs.get("PostId")
            raw_created = attrs.get("CreationDate")
            if raw_post_id is None or raw_created is None:
                continue

            post_id = int(raw_post_id)
            if post_id in question_ids:
                qid = post_id
                source_key = "question_comment"
            elif post_id in answer_to_question:
                qid = answer_to_question[post_id]
                source_key = "answer_comment"
            else:
                continue

            text = clean_text(attrs.get("Text", "") or "")
            broad_labels = match_text(text, broad_compiled)
            strict_labels = match_text(text, strict_compiled)
            if not broad_labels and not strict_labels:
                continue

            created_at = pd.Timestamp(raw_created, tz="UTC")
            row = hits.setdefault(qid, init_row(qid, metadata))
            update_hit(row, "broad", source_key, broad_labels, created_at)
            update_hit(row, "strict", source_key, strict_labels, created_at)

    return hits


def finalize_hits(hits: dict[int, dict[str, object]]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for row in hits.values():
        broad_counter = row.pop("_broad_labels")
        strict_counter = row.pop("_strict_labels")
        row["broad_match_labels"] = ";".join(sorted(broad_counter.keys()))
        row["strict_match_labels"] = ";".join(sorted(strict_counter.keys()))
        row["n_broad_labels"] = len(broad_counter)
        row["n_strict_labels"] = len(strict_counter)
        row["days_from_ban"] = float((row["question_created_at"] - BAN_TS).total_seconds() / 86400.0)
        row["post_ban_question"] = int(row["question_created_at"] >= BAN_TS)
        rows.append(row)

    if not rows:
        return pd.DataFrame()

    df = pd.DataFrame(rows).sort_values(["question_created_at", "question_id"]).reset_index(drop=True)
    return df


def build_counts(df: pd.DataFrame, total_questions: int) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, object]]:
    if df.empty:
        counts = pd.DataFrame([{"metric": "total_questions", "value": total_questions}])
        ban = pd.DataFrame()
        summary = {
            "posthistory_available": False,
            "comments_available": COMMENTS_XML.exists(),
            "total_questions": total_questions,
            "broad_thread_hits": 0,
            "strict_thread_hits": 0,
        }
        return counts, ban, summary

    counts_rows = [
        ("posthistory_available", 0),
        ("comments_available", int(COMMENTS_XML.exists())),
        ("total_questions", total_questions),
        ("broad_thread_hits", int(df["broad_any_thread_hit"].sum())),
        ("strict_thread_hits", int(df["strict_any_thread_hit"].sum())),
        ("strict_question_side_hits", int(df["strict_question_side_hit"].sum())),
        ("strict_answer_side_hits", int(df["strict_answer_side_hit"].sum())),
        ("broad_title_hits", int(df["broad_title_hit"].sum())),
        ("broad_question_body_hits", int(df["broad_question_body_hit"].sum())),
        ("broad_answer_body_hits", int(df["broad_answer_body_hit"].sum())),
        ("broad_question_comment_hits", int(df["broad_question_comment_hit"].sum())),
        ("broad_answer_comment_hits", int(df["broad_answer_comment_hit"].sum())),
        ("strict_title_hits", int(df["strict_title_hit"].sum())),
        ("strict_question_body_hits", int(df["strict_question_body_hit"].sum())),
        ("strict_answer_body_hits", int(df["strict_answer_body_hit"].sum())),
        ("strict_question_comment_hits", int(df["strict_question_comment_hit"].sum())),
        ("strict_answer_comment_hits", int(df["strict_answer_comment_hit"].sum())),
        ("broad_share", float(df["broad_any_thread_hit"].sum() / total_questions)),
        ("strict_share", float(df["strict_any_thread_hit"].sum() / total_questions)),
    ]
    counts = pd.DataFrame(counts_rows, columns=["metric", "value"])

    tag_month = (
        df.groupby(["primary_tag", "month_id"], as_index=False)
        .agg(
            questions=("question_id", "size"),
            broad_thread_hits=("broad_any_thread_hit", "sum"),
            strict_thread_hits=("strict_any_thread_hit", "sum"),
            strict_question_side_hits=("strict_question_side_hit", "sum"),
            strict_answer_side_hits=("strict_answer_side_hit", "sum"),
            high_tag=("high_tag", "first"),
            exposure_index=("exposure_index", "first"),
        )
    )
    tag_month.to_csv(TAG_MONTH_CSV, index=False)

    ban_rows = []
    for window in WINDOW_DAYS:
        lo = BAN_TS - pd.Timedelta(days=window)
        hi = BAN_TS + pd.Timedelta(days=window)
        subset = df.loc[(df["question_created_at"] >= lo) & (df["question_created_at"] <= hi)].copy()
        for side, col in [
            ("broad", "broad_any_thread_hit"),
            ("strict", "strict_any_thread_hit"),
            ("strict_question_side", "strict_question_side_hit"),
            ("strict_answer_side", "strict_answer_side_hit"),
        ]:
            pre = subset.loc[subset["question_created_at"] < BAN_TS, col].sum()
            post = subset.loc[subset["question_created_at"] >= BAN_TS, col].sum()
            pre_n = int((subset["question_created_at"] < BAN_TS).sum())
            post_n = int((subset["question_created_at"] >= BAN_TS).sum())
            ban_rows.append(
                {
                    "window_days": window,
                    "series": side,
                    "pre_hits": int(pre),
                    "post_hits": int(post),
                    "pre_questions": pre_n,
                    "post_questions": post_n,
                    "pre_share": float(pre / pre_n) if pre_n else 0.0,
                    "post_share": float(post / post_n) if post_n else 0.0,
                }
            )
    ban = pd.DataFrame(ban_rows)

    broad_labels = Counter()
    strict_labels = Counter()
    for labels in df["broad_match_labels"].tolist():
        if labels:
            broad_labels.update(labels.split(";"))
    for labels in df["strict_match_labels"].tolist():
        if labels:
            strict_labels.update(labels.split(";"))

    summary = {
        "posthistory_available": False,
        "comments_available": COMMENTS_XML.exists(),
        "total_questions": total_questions,
        "broad_thread_hits": int(df["broad_any_thread_hit"].sum()),
        "strict_thread_hits": int(df["strict_any_thread_hit"].sum()),
        "broad_share": float(df["broad_any_thread_hit"].sum() / total_questions),
        "strict_share": float(df["strict_any_thread_hit"].sum() / total_questions),
        "strict_question_side_hits": int(df["strict_question_side_hit"].sum()),
        "strict_answer_side_hits": int(df["strict_answer_side_hit"].sum()),
        "top_broad_patterns": broad_labels.most_common(10),
        "top_strict_patterns": strict_labels.most_common(10),
        "top_tags_broad": df.loc[df["broad_any_thread_hit"] == 1, "primary_tag"].value_counts().head(10).to_dict(),
        "top_tags_strict": df.loc[df["strict_any_thread_hit"] == 1, "primary_tag"].value_counts().head(10).to_dict(),
    }
    return counts, ban, summary


def write_memo(summary: dict[str, object], counts: pd.DataFrame, ban: pd.DataFrame) -> None:
    count_map = {row["metric"]: row["value"] for _, row in counts.iterrows()}
    lines = [
        "# Posthistory-Style Direct-AI Layer (Current-Thread Upgrade)",
        "",
        "Date: April 5, 2026",
        "",
        "## What was feasible",
        "",
        "Local official dump assets did not include `PostHistory.xml`, so a true edit-history direct-observation layer was not feasible in this run.",
        "The strongest same-setting upgrade was therefore built from official current-thread data: question titles, question bodies, answer bodies, question comments, and answer comments from the local Stack Overflow dump.",
        "",
        "## Design",
        "",
        "This layer separates two ideas:",
        "",
        "- `broad disclosed-AI`: any explicit AI-tool mention anywhere in the current thread",
        "- `strict direct-observation`: narrower self-disclosure patterns that are closer to explicit AI use rather than generic tool mention",
        "",
        "The sample is aligned to the canonical single-focal-question backbone rather than the larger exploratory pool.",
        "",
        "## Topline",
        "",
        f"- canonical single-focal questions scanned: `{int(count_map.get('total_questions', 0)):,}`",
        f"- broad thread-level disclosed-AI hits: `{int(count_map.get('broad_thread_hits', 0)):,}` (`{float(count_map.get('broad_share', 0.0)):.4%}`)",
        f"- strict direct-observation hits: `{int(count_map.get('strict_thread_hits', 0)):,}` (`{float(count_map.get('strict_share', 0.0)):.4%}`)",
        f"- strict question-side hits: `{int(count_map.get('strict_question_side_hits', 0)):,}`",
        f"- strict answer-side hits: `{int(count_map.get('strict_answer_side_hits', 0)):,}`",
        f"- comments available locally: `{bool(count_map.get('comments_available', 0))}`",
        f"- posthistory available locally: `{bool(count_map.get('posthistory_available', 0))}`",
        "",
        "## Why this is stronger than the old layer",
        "",
        "The old title-only prototype could only see explicit AI disclosure when it appeared in question titles.",
        "The current upgrade uses full current-thread evidence and distinguishes broad mentions from a stricter self-disclosure layer.",
        "That is still selective, but it is materially closer to direct observation because it captures explicit in-thread disclosure in bodies and comments rather than only in titles.",
        "",
        "## Ban-window read",
        "",
    ]
    if ban.empty:
        lines.append("- No ban-window counts were available.")
    else:
        for _, row in ban.iterrows():
            if row["window_days"] in {30, 60} and row["series"] in {"broad", "strict", "strict_question_side"}:
                lines.append(
                    f"- `+/-{int(row['window_days'])}d`, `{row['series']}`: pre-share `{row['pre_share']:.4%}`, post-share `{row['post_share']:.4%}`"
                )

    lines += [
        "",
        "## Safe read",
        "",
        "This is still a bounded direct-observation layer, not universal AI-use measurement.",
        "It improves the paper in two specific ways:",
        "",
        "1. It provides a same-setting thread-level disclosed-AI corpus aligned to the canonical single-focal sample.",
        "2. It creates a stricter subset that is closer to explicit self-disclosed AI use than the earlier broad or title-only layers.",
        "",
        "Its main limit is still selection: only users who explicitly disclose AI use inside the current thread can be observed.",
        "",
        "## Files",
        "",
        f"- question hits parquet: `{QUESTION_HITS_PARQUET}`",
        f"- question hits csv: `{QUESTION_HITS_CSV}`",
        f"- counts csv: `{COUNTS_CSV}`",
        f"- tag-month counts csv: `{TAG_MONTH_CSV}`",
        f"- ban-window counts csv: `{BAN_WINDOW_CSV}`",
        f"- summary json: `{SUMMARY_JSON}`",
    ]
    MEMO_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    PROCESSED.mkdir(parents=True, exist_ok=True)
    PAPER.mkdir(parents=True, exist_ok=True)

    metadata, question_ids = load_question_metadata()
    answer_to_question = load_answer_mapping(question_ids)
    broad_compiled = compile_patterns(BROAD_PATTERNS)
    strict_compiled = compile_patterns(STRICT_PATTERNS)

    hits = parse_post_rows(question_ids, answer_to_question, metadata, broad_compiled, strict_compiled)
    hits = parse_comment_rows(hits, question_ids, answer_to_question, metadata, broad_compiled, strict_compiled)
    df = finalize_hits(hits)

    if not df.empty:
        df.to_parquet(QUESTION_HITS_PARQUET, index=False)
        df.to_csv(QUESTION_HITS_CSV, index=False)

    counts, ban, summary = build_counts(df, len(question_ids))
    counts.to_csv(COUNTS_CSV, index=False)
    ban.to_csv(BAN_WINDOW_CSV, index=False)
    SUMMARY_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    write_memo(summary, counts, ban)

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
