from __future__ import annotations

import html
import json
import re
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "processed"
RAW = ROOT / "raw"
PAPER = ROOT / "paper"

QUESTION_PANEL = PROCESSED / "stackexchange_20251231_question_level_enriched.parquet"
FOCAL_ANSWERS = PROCESSED / "stackexchange_20251231_focal_answers.parquet"
ANSWER_USER_TAG_MONTH = PROCESSED / "who_still_answers_user_tag_month_panel.parquet"
POSTS_XML = RAW / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Posts.xml"
COMMENTS_XML = RAW / "stackexchange_20251231" / "stackoverflow.com_extracted" / "Comments.xml"

POST_CANDIDATES = PROCESSED / "who_still_answers_disclosed_ai_post_candidates.txt"
COMMENT_CANDIDATES = PROCESSED / "who_still_answers_disclosed_ai_comment_candidates.txt"

EVENTS_PARQUET = PROCESSED / "p1_genai_author_linked_disclosure_events.parquet"
EVENTS_CSV = PROCESSED / "p1_genai_author_linked_disclosure_events.csv"
USER_MONTH_PARQUET = PROCESSED / "p1_genai_author_linked_disclosure_user_month_panel.parquet"
USER_MONTH_CSV = PROCESSED / "p1_genai_author_linked_disclosure_user_month_panel.csv"
SUMMARY_JSON = PROCESSED / "p1_genai_author_linked_disclosure_summary.json"
VARIABLES_JSON = PROCESSED / "p1_genai_author_linked_disclosure_variables.json"

READOUT_PATH = PAPER / "p1_genai_author_linked_disclosure_readout_2026-04-06.md"

BROAD_PATTERNS = {
    "chatgpt": r"\bchatgpt\b",
    "copilot": r"\b(?:github\s+)?copilot\b",
    "claude": r"\bclaude(?:\s+code|\s+ai)?\b|claude[- ]code",
    "gemini": r"\b(?:google\s+)?gemini(?:\s+(?:ai|pro|flash|nano|1\.5|2(?:\.0)?))?\b",
    "deepseek": r"\bdeepseek\b",
    "openai": r"\bopenai\b",
    "anthropic": r"\banthropic\b",
    "bard": r"\bgoogle\s+bard\b|\bbard\s+ai\b",
    "gpt_family": r"\bgpt[- ]?(?:3|3\.5|4|4o|4\.1|4\.5|5|o1|o3|o4)\b|\bgenerative pre[- ]trained\b",
    "llm": r"\blarge language model(?:s)?\b|\bllm(?:s)?\b",
    "ai_generated": r"\b(?:ai[- ]generated|generated by (?:chatgpt|openai|ai)|written by (?:chatgpt|openai|ai)|created by (?:chatgpt|openai|ai))\b",
}

STRICT_PATTERNS = {
    "used_tool": r"\b(?:i|we|my|our)\s+(?:used|use|using|tried|ask(?:ed)?|prompt(?:ed)?|fed|gave|ran)\s+(?:chatgpt|copilot|claude|gemini|deepseek|openai|gpt(?:[- ]?\d(?:\.\d)?)?|llm|ai)\b",
    "tool_generated": r"\b(?:generated|written|produced|created|suggested|drafted)\s+(?:by|with)\s+(?:chatgpt|copilot|claude|gemini|deepseek|openai|gpt(?:[- ]?\d(?:\.\d)?)?|ai)\b",
    "from_tool": r"\b(?:from|via|using)\s+(?:chatgpt|copilot|claude|gemini|deepseek|openai|gpt(?:[- ]?\d(?:\.\d)?)?|llm)\b",
    "tool_said": r"\b(?:chatgpt|copilot|claude|gemini|deepseek|gpt(?:[- ]?\d(?:\.\d)?)?)(?:\s+(?:says|said|suggested|gave|returns?|wrote|generated))\b",
    "ai_assisted": r"\b(?:ai[- ]assisted|llm[- ]assisted|copilot[- ]generated|gpt[- ]generated)\b",
}

COARSE_HINT = re.compile(
    r"chatgpt|copilot|openai|anthropic|claude|deepseek|gemini|bard|llm|gpt|language model|ai-generated|ai assisted",
    flags=re.IGNORECASE,
)
HTML_TAG = re.compile(r"<[^>]+>")


def clean_text(text: str) -> str:
    if not text:
        return ""
    cleaned = HTML_TAG.sub(" ", text)
    cleaned = html.unescape(cleaned)
    return re.sub(r"\s+", " ", cleaned).strip()


def compile_patterns(patterns: dict[str, str]) -> dict[str, re.Pattern[str]]:
    return {label: re.compile(pattern, flags=re.IGNORECASE) for label, pattern in patterns.items()}


def match_text(text: str, compiled: dict[str, re.Pattern[str]]) -> list[str]:
    if not text:
        return []
    return [label for label, pattern in compiled.items() if pattern.search(text)]


def load_question_metadata() -> tuple[pd.DataFrame, dict[int, dict[str, object]], set[int]]:
    cols = [
        "question_id",
        "question_created_at",
        "owner_user_id",
        "title",
        "primary_tag",
        "month_id",
        "high_tag",
        "exposure_index",
        "post_chatgpt",
        "keep_single_focal",
    ]
    q = pd.read_parquet(QUESTION_PANEL, columns=cols).copy()
    q = q.loc[q["keep_single_focal"] == 1].copy()
    q["question_id"] = q["question_id"].astype(int)
    q["owner_user_id"] = pd.to_numeric(q["owner_user_id"], errors="coerce").astype("Int64")
    q["question_created_at"] = pd.to_datetime(q["question_created_at"], utc=True)
    q["month_id"] = q["month_id"].astype(str)
    question_meta = q.set_index("question_id").to_dict("index")
    return q, question_meta, set(q["question_id"].tolist())


def load_answer_metadata(question_ids: set[int]) -> tuple[dict[int, int], dict[int, dict[str, object]]]:
    answers = pd.read_parquet(FOCAL_ANSWERS).copy()
    answers["answer_id"] = answers["answer_id"].astype(int)
    answers["question_id"] = answers["question_id"].astype(int)
    answers["owner_user_id"] = pd.to_numeric(answers["owner_user_id"], errors="coerce").astype("Int64")
    answers["answer_created_at"] = pd.to_datetime(answers["answer_created_at"], utc=True)
    answers = answers.loc[answers["question_id"].isin(question_ids)].copy()
    answer_to_question = dict(zip(answers["answer_id"], answers["question_id"]))
    answer_meta = answers.set_index("answer_id").to_dict("index")
    return answer_to_question, answer_meta


def infer_tool_family(text: str, broad_compiled: dict[str, re.Pattern[str]]) -> str:
    labels = match_text(text, broad_compiled)
    return ";".join(sorted(labels))


def make_event_row(
    *,
    user_id: int | None,
    role: str,
    source_surface: str,
    event_ts: pd.Timestamp,
    question_id: int,
    answer_id: int | None,
    comment_id: int | None,
    strict_labels: list[str],
    tool_labels: str,
    meta: dict[str, object],
) -> dict[str, object]:
    return {
        "user_id": user_id,
        "role": role,
        "source_surface": source_surface,
        "event_ts": event_ts,
        "event_month": str(event_ts.to_period("M")),
        "question_id": question_id,
        "answer_id": answer_id,
        "comment_id": comment_id,
        "strict_pattern_labels": ";".join(sorted(strict_labels)),
        "tool_family_labels": tool_labels,
        "question_created_at": meta["question_created_at"],
        "question_month_id": meta["month_id"],
        "primary_tag": meta["primary_tag"],
        "high_tag": meta["high_tag"],
        "exposure_index": meta["exposure_index"],
        "post_chatgpt": meta["post_chatgpt"],
    }


def parse_posts(
    question_ids: set[int],
    question_meta: dict[int, dict[str, object]],
    answer_to_question: dict[int, int],
    answer_meta: dict[int, dict[str, object]],
    broad_compiled: dict[str, re.Pattern[str]],
    strict_compiled: dict[str, re.Pattern[str]],
) -> list[dict[str, object]]:
    events: list[dict[str, object]] = []
    source_path = POST_CANDIDATES if POST_CANDIDATES.exists() else POSTS_XML
    with source_path.open("r", encoding="utf-8", errors="ignore", buffering=1024 * 1024) as handle:
        for line in handle:
            if "<row " not in line or COARSE_HINT.search(line) is None:
                continue
            try:
                attrs = ET.fromstring(line.strip()).attrib
            except ET.ParseError:
                continue

            post_type = attrs.get("PostTypeId")
            if post_type not in {"1", "2"}:
                continue

            raw_id = attrs.get("Id")
            if raw_id is None:
                continue
            post_id = int(raw_id)

            if post_type == "1" and post_id in question_ids:
                meta = question_meta[post_id]
                title = str(meta.get("title") or "")
                body = clean_text(attrs.get("Body", "") or "")
                title_strict = match_text(title, strict_compiled)
                body_strict = match_text(body, strict_compiled)
                user_id = int(meta["owner_user_id"]) if pd.notna(meta["owner_user_id"]) else None

                if title_strict:
                    events.append(
                        make_event_row(
                            user_id=user_id,
                            role="asker",
                            source_surface="title",
                            event_ts=meta["question_created_at"],
                            question_id=post_id,
                            answer_id=None,
                            comment_id=None,
                            strict_labels=title_strict,
                            tool_labels=infer_tool_family(title, broad_compiled),
                            meta=meta,
                        )
                    )
                if body_strict:
                    events.append(
                        make_event_row(
                            user_id=user_id,
                            role="asker",
                            source_surface="question_body",
                            event_ts=meta["question_created_at"],
                            question_id=post_id,
                            answer_id=None,
                            comment_id=None,
                            strict_labels=body_strict,
                            tool_labels=infer_tool_family(body, broad_compiled),
                            meta=meta,
                        )
                    )

            elif post_type == "2" and post_id in answer_to_question:
                question_id = answer_to_question[post_id]
                meta = question_meta[question_id]
                answer_info = answer_meta[post_id]
                body = clean_text(attrs.get("Body", "") or "")
                body_strict = match_text(body, strict_compiled)
                if body_strict:
                    user_id = (
                        int(answer_info["owner_user_id"])
                        if pd.notna(answer_info["owner_user_id"])
                        else None
                    )
                    events.append(
                        make_event_row(
                            user_id=user_id,
                            role="answerer",
                            source_surface="answer_body",
                            event_ts=answer_info["answer_created_at"],
                            question_id=question_id,
                            answer_id=post_id,
                            comment_id=None,
                            strict_labels=body_strict,
                            tool_labels=infer_tool_family(body, broad_compiled),
                            meta=meta,
                        )
                    )

    return events


def parse_comments(
    events: list[dict[str, object]],
    question_ids: set[int],
    question_meta: dict[int, dict[str, object]],
    answer_to_question: dict[int, int],
    broad_compiled: dict[str, re.Pattern[str]],
    strict_compiled: dict[str, re.Pattern[str]],
) -> list[dict[str, object]]:
    if not COMMENTS_XML.exists():
        return events

    source_path = COMMENT_CANDIDATES if COMMENT_CANDIDATES.exists() else COMMENTS_XML
    with source_path.open("r", encoding="utf-8", errors="ignore", buffering=1024 * 1024) as handle:
        for line in handle:
            if "<row " not in line or COARSE_HINT.search(line) is None:
                continue
            try:
                attrs = ET.fromstring(line.strip()).attrib
            except ET.ParseError:
                continue

            raw_post_id = attrs.get("PostId")
            raw_comment_id = attrs.get("Id")
            raw_user_id = attrs.get("UserId")
            raw_created = attrs.get("CreationDate")
            if raw_post_id is None or raw_comment_id is None or raw_created is None:
                continue

            post_id = int(raw_post_id)
            comment_id = int(raw_comment_id)
            event_ts = pd.Timestamp(raw_created, tz="UTC")
            user_id = int(raw_user_id) if raw_user_id is not None else None

            if post_id in question_ids:
                question_id = post_id
                role = "question_commenter"
                source_surface = "question_comment"
                answer_id = None
            elif post_id in answer_to_question:
                question_id = answer_to_question[post_id]
                role = "answer_commenter"
                source_surface = "answer_comment"
                answer_id = post_id
            else:
                continue

            text = clean_text(attrs.get("Text", "") or "")
            strict_labels = match_text(text, strict_compiled)
            if not strict_labels:
                continue

            meta = question_meta[question_id]
            events.append(
                make_event_row(
                    user_id=user_id,
                    role=role,
                    source_surface=source_surface,
                    event_ts=event_ts,
                    question_id=question_id,
                    answer_id=answer_id,
                    comment_id=comment_id,
                    strict_labels=strict_labels,
                    tool_labels=infer_tool_family(text, broad_compiled),
                    meta=meta,
                )
            )

    return events


def build_user_month_panel(events: pd.DataFrame) -> pd.DataFrame:
    if events.empty:
        return pd.DataFrame()

    grouped = (
        events.groupby(["user_id", "event_month"], as_index=False)
        .agg(
            direct_ai_events=("question_id", "size"),
            ask_events=("role", lambda s: int((s == "asker").sum())),
            answer_events=("role", lambda s: int((s == "answerer").sum())),
            question_comment_events=("role", lambda s: int((s == "question_commenter").sum())),
            answer_comment_events=("role", lambda s: int((s == "answer_commenter").sum())),
            distinct_questions=("question_id", "nunique"),
            distinct_answers=("answer_id", lambda s: int(pd.Series(s).dropna().nunique())),
            distinct_tools=("tool_family_labels", lambda s: int(pd.Series(s).replace("", np.nan).dropna().nunique())),
            high_tag_event_share=("high_tag", "mean"),
            mean_exposure_index=("exposure_index", "mean"),
        )
        .sort_values(["user_id", "event_month"])
        .reset_index(drop=True)
    )
    first_event = grouped.drop_duplicates("user_id", keep="first")[["user_id", "event_month"]].rename(
        columns={"event_month": "first_direct_ai_month"}
    )
    grouped = grouped.merge(first_event, on="user_id", how="left")
    grouped["event_month_index"] = pd.PeriodIndex(grouped["event_month"], freq="M").asi8
    grouped["first_direct_ai_month_index"] = pd.PeriodIndex(grouped["first_direct_ai_month"], freq="M").asi8
    grouped["months_since_first_direct_ai"] = (
        grouped["event_month_index"] - grouped["first_direct_ai_month_index"]
    )
    grouped["cumulative_direct_ai_events"] = grouped.groupby("user_id")["direct_ai_events"].cumsum()
    grouped["repeat_direct_ai_month"] = (grouped["cumulative_direct_ai_events"] > grouped["direct_ai_events"]).astype(int)
    return grouped


def build_summary(events: pd.DataFrame, user_month: pd.DataFrame) -> dict[str, object]:
    role_counts = events["role"].value_counts().to_dict() if not events.empty else {}
    surface_counts = events["source_surface"].value_counts().to_dict() if not events.empty else {}
    tool_counts = Counter()
    for labels in events.get("tool_family_labels", pd.Series(dtype=str)).fillna(""):
        if labels:
            tool_counts.update(labels.split(";"))

    summary = {
        "n_events": int(len(events)),
        "n_users": int(events["user_id"].dropna().nunique()) if not events.empty else 0,
        "n_questions": int(events["question_id"].nunique()) if not events.empty else 0,
        "n_answer_side_events": int((events["role"] == "answerer").sum()) if not events.empty else 0,
        "n_comment_side_events": int(events["role"].isin(["question_commenter", "answer_commenter"]).sum()) if not events.empty else 0,
        "role_counts": role_counts,
        "surface_counts": surface_counts,
        "top_tool_families": tool_counts.most_common(10),
        "n_user_months": int(len(user_month)),
        "n_repeat_direct_ai_user_months": int(user_month["repeat_direct_ai_month"].sum()) if not user_month.empty else 0,
    }
    return summary


def write_readout(summary: dict[str, object]) -> None:
    lines = [
        "# P1 Author-Linked Direct-Disclosure Events",
        "",
        "Date: `2026-04-06`",
        "",
        "## Scope",
        "",
        "This build upgrades the paper's telemetry-adjacent layer from a narrow title/tag disclosure proxy to an author-linked direct-disclosure event panel built from the local Stack Overflow dump.",
        "",
        "## Safe Read",
        "",
        "This is still not telemetry. It observes explicit in-thread self-disclosure or tool-attributed AI use episodes, not universal or private AI adoption.",
        "",
        "## Headline Counts",
        "",
        f"- direct-disclosure events: `{summary['n_events']:,}`",
        f"- users with at least one event: `{summary['n_users']:,}`",
        f"- focal questions touched: `{summary['n_questions']:,}`",
        f"- answer-side events: `{summary['n_answer_side_events']:,}`",
        f"- comment-side events: `{summary['n_comment_side_events']:,}`",
        f"- user-months with at least one direct-disclosure event: `{summary['n_user_months']:,}`",
        f"- repeat direct-disclosure user-months: `{summary['n_repeat_direct_ai_user_months']:,}`",
        "",
        "## Role Mix",
        "",
    ]
    for role, count in summary["role_counts"].items():
        lines.append(f"- `{role}`: `{count:,}`")

    lines += [
        "",
        "## Surface Mix",
        "",
    ]
    for surface, count in summary["surface_counts"].items():
        lines.append(f"- `{surface}`: `{count:,}`")

    lines += [
        "",
        "## Why This Matters",
        "",
        "This layer is materially closer to direct adoption evidence because it attributes explicit AI-use disclosures to specific users and roles rather than only counting question-side title/tag hits.",
        "",
        "Its limit is still selection: only users who explicitly disclose AI use inside the visible thread are observed.",
        "",
        "## Files",
        "",
        f"- events parquet: `{EVENTS_PARQUET}`",
        f"- events csv: `{EVENTS_CSV}`",
        f"- user-month panel parquet: `{USER_MONTH_PARQUET}`",
        f"- user-month panel csv: `{USER_MONTH_CSV}`",
        f"- summary json: `{SUMMARY_JSON}`",
    ]
    READOUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_variables_note() -> None:
    payload = {
        "unit": "author-linked direct-disclosure event",
        "telemetry_present": False,
        "safe_label": "author-linked direct-disclosure event evidence",
        "roles": ["asker", "answerer", "question_commenter", "answer_commenter"],
        "surfaces": ["title", "question_body", "answer_body", "question_comment", "answer_comment"],
        "key_fields": [
            "user_id",
            "role",
            "source_surface",
            "event_ts",
            "event_month",
            "question_id",
            "answer_id",
            "comment_id",
            "strict_pattern_labels",
            "tool_family_labels",
            "primary_tag",
            "high_tag",
            "exposure_index",
        ],
    }
    VARIABLES_JSON.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main() -> None:
    PROCESSED.mkdir(parents=True, exist_ok=True)
    PAPER.mkdir(parents=True, exist_ok=True)

    broad_compiled = compile_patterns(BROAD_PATTERNS)
    strict_compiled = compile_patterns(STRICT_PATTERNS)

    _, question_meta, question_ids = load_question_metadata()
    answer_to_question, answer_meta = load_answer_metadata(question_ids)

    events = parse_posts(
        question_ids,
        question_meta,
        answer_to_question,
        answer_meta,
        broad_compiled,
        strict_compiled,
    )
    events = parse_comments(
        events,
        question_ids,
        question_meta,
        answer_to_question,
        broad_compiled,
        strict_compiled,
    )

    if events:
        df = pd.DataFrame(events).sort_values(
            ["event_ts", "question_id", "answer_id", "comment_id", "role", "source_surface"]
        ).reset_index(drop=True)
        df.insert(0, "event_id", [f"DAE-{i+1:07d}" for i in range(len(df))])
    else:
        df = pd.DataFrame(
            columns=[
                "event_id",
                "user_id",
                "role",
                "source_surface",
                "event_ts",
                "event_month",
                "question_id",
                "answer_id",
                "comment_id",
                "strict_pattern_labels",
                "tool_family_labels",
                "question_created_at",
                "question_month_id",
                "primary_tag",
                "high_tag",
                "exposure_index",
                "post_chatgpt",
            ]
        )

    user_month = build_user_month_panel(df)
    summary = build_summary(df, user_month)

    df.to_parquet(EVENTS_PARQUET, index=False)
    df.to_csv(EVENTS_CSV, index=False)
    user_month.to_parquet(USER_MONTH_PARQUET, index=False)
    user_month.to_csv(USER_MONTH_CSV, index=False)
    SUMMARY_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    write_variables_note()
    write_readout(summary)

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
